platform :ios, '9.0'

target 'Newspedia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Newspedia
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
